### ISSUE TITLE
Setting Kanban for Ruby Group Project

### ISSUE THREAD

**Issue by PowerLevel9000** [PowerLevel9000/Catalog#14]
# Setting Kanban for Ruby Group Project

## project link => <a href="https://github.com/PowerLevel9000/Catalog/projects/1">click me </a>

- [ ] set kanban according to the given UML diagram in the curriculum 
- [ ] assign task to respective Team members 

# happy developing 
![BoomAsherSternGIF](https://user-images.githubusercontent.com/116451144/235469430-4c84f3d9-7108-44b8-909f-8f6717fbef0d.gif)

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Group work ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! In this group task #4, you forgot to assign this member @HanaSabih, please assign all team members to group tasks 🙏🏼 

 
![image](https://user-images.githubusercontent.com/63915024/235479531-c367cb68-df7d-4e61-a7db-2ea35a4aa208.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gambit142** [comment]
Hi @HanaSabih @LeslieAine @PowerLevel9000 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Created Kanban Board ✔️ 
- All cards are assigned to a team member ✔️ 
- All project requirements for team members and group tasks have a corresponding card ✔️

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PowerLevel9000** [comment]
# Thank you 💪💪💪🙏🙏🙏

![ThankYouSoMuchPrabhasGIF](https://user-images.githubusercontent.com/116451144/233258767-f3943ca4-fbe2-4fde-b8b1-2129593266e5.gif)


Dear @Gambit142 @mukhammadrizooff ,

I wanted to express my gratitude for your willingness to take the time to review my code on GitHub. Your feedback and suggestions have been instrumental in improving the quality of my work, and I appreciate your insights and expertise in this area.

It's inspiring to have someone like you, who is knowledgeable and experienced, provide valuable feedback that helps me enhance my coding skills. I truly appreciate the time and effort you put into reviewing my code, and I'm grateful for your constructive criticism.

If there are any areas that I need to work on, please don't hesitate to let me know. I'm open to hearing any suggestions or recommendations you may have. Your feedback is essential to my growth as a developer, and I value it tremendously.

Thank you again for your time and for sharing your expertise with me. I'm looking forward to applying the insights gained from your review to my future projects.

Sincerely,
@PowerLevel9000
